### ISSUE TITLE
5 land marks head pose estimation

### ISSUE THREAD

**Issue by andriy-gerasika** [lincolnhard/head-pose-estimation#3]
Hello,
your code is very nice and works ok.

Can you please try and adapt it for newly released Dlib's 5 point landmark detection? I have tried to adapt the code by myself, but the data is way off.

Is it actually possible or are five landmarks not enough to reconstruct 3D head pose?

Thanks!

**Comment by andriy-gerasika** [comment]
incorrectly calibrated camera...

**Comment by lincolnhard** [comment]
Thanks for your feedback.
5 point landmark detection looks cool.
I think its a good idea, will try to use them to make some toy app in free time.
